---
- name: configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - python-pip
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - amazon-linux-extras

- name: Add extras repository
  shell: yum-config-manager --enable extras
