- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install ufw
  apt:
    package: ufw
    state: present

- name: Enable ufw
  ufw: state=enabled
