---
- name: Copy gitlab.rb
  template:
    src: gitlab.rb.j2
    dest: /gitlab/config/gitlab.rb

- name: Copy SSL cert
  copy:
    src: "/etc/ansible/roles/gitlab/files/cert.pem"
    dest: "/gitlab/config/ssl/cert.pem"
    mode: '0755'

- name: Copy SSL key
  copy:
    src: "/etc/ansible/roles/gitlab/files/privkey.pem"
    dest: "/gitlab/config/ssl/privkey.pem"
    mode: '0755'

- name: Increase swap size
  become: true
  shell: echo 'CONF_SWAPSIZE=4096\nCONF_MAXSWAP=4096' > /etc/dphys-swapfile 

- name: Restart swapfile service
  become: true
  shell: /etc/init.d/dphys-swapfile restart

- name: Ensure Docker Installed
  pip:
    name: docker

- name: Pull gitlab image
  docker_image: 
    name: "{{ gitlab_image_tag }}"
    source: pull

- name: Create gitlab container on Pi
  docker_container:
    name: gitlab
    image: "{{ gitlab_image_tag }}"
    hostname: gitlab.mahoney0101.com
    ports:
      - "443:443"
      - "80:80"
      - "2222:22"
    restart_policy: always
    volumes:
      - /gitlab/config:/etc/gitlab
      - /gitlab/logs:/var/log/gitlab
      - /gitlab/data:/var/opt/gitlab
    recreate: yes
